services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-nodes-bannerbite
    restart: unless-stopped
    ports:
      - '5678:5678'
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - NODE_ENV=development
      - N8N_USER_FOLDER=/usr/local/lib/node_modules/n8n/.n8n
      - N8N_CUSTOM_EXTENSIONS=/usr/local/lib/node_modules/n8n/.n8n/custom
      - N8N_LOAD_FROM_FILE=false
      - N8N_ENCRYPTION_KEY=your-secret-encryption-key
      - N8N_DIAGNOSTICS_ENABLED=true
      - N8N_LOG_LEVEL=debug
    volumes:
      - n8n_data:/usr/local/lib/node_modules/n8n/.n8n
    user: "node"  # Ensure we're running as node user

volumes:
  n8n_data:
    name: n8n-nodes-bannerbite-data